const META_KEYS=['dance.catalog-snapshot','dance.repertoire-snapshot','dance.offline.manifest','dance.program','dance.trash','dance.file-results'] as const;
let lastOrder=0;let database:IDBDatabase|null=null;const memory=new Map<string,string>();
function request<T>(req:IDBRequest<T>):Promise<T>{return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
export async function initializeLocalDatabase(){if(!globalThis.indexedDB)return;database?.close();memory.clear();const open=indexedDB.open('dance-library',1);open.onupgradeneeded=()=>{const db=open.result;db.createObjectStore('metadata');db.createObjectStore('operations',{keyPath:'operationId'});db.createObjectStore('files',{keyPath:'id'});};database=await request(open);
 for(const key of META_KEYS){let value=await request(database.transaction('metadata').objectStore('metadata').get(key)) as string|undefined;if(value===undefined){const legacy=localStorage.getItem(key);if(legacy!==null){JSON.parse(legacy);await commitLocal({[key]:legacy});value=await request(database.transaction('metadata').objectStore('metadata').get(key));if(value!==legacy)throw Error('旧数据迁移校验失败');}}if(value!==undefined)memory.set(key,value);}
}
export function readMetadata(key:string):string|null{return memory.get(key)??localStorage.getItem(key);}
export async function commitLocal(values:Record<string,string>,operations:unknown[]=[],deleteOperations:string[]=[]){if(!database)throw Error('本地数据库不可用，修改尚未保存');const tx=database.transaction(['metadata','operations'],'readwrite');const done=new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error||Error('手机存储空间不足'));tx.onerror=()=>reject(tx.error);});for(const [key,value] of Object.entries(values))tx.objectStore('metadata').put(value,key);for(const op of operations){const value=op as Record<string,unknown>;tx.objectStore('operations').put({...value,createdAt:value.createdAt??(lastOrder=Math.max(Date.now()*1000,lastOrder+1))});}for(const id of deleteOperations)tx.objectStore('operations').delete(id);await done;for(const [key,value] of Object.entries(values)){memory.set(key,value);try{localStorage.setItem(key,value);}catch{/* IndexedDB already durably committed. */}}window.dispatchEvent(new Event('dance-local-changed'));}
export function writeMetadata(key:string,value:string){memory.set(key,value);localStorage.setItem(key,value);if(database)void commitLocal({[key]:value}).catch(()=>window.dispatchEvent(new Event('dance-storage-error')));}
export async function localOperations<T>():Promise<T[]>{const ops=database?await request(database.transaction('operations').objectStore('operations').getAll()) as (T&{createdAt?:number})[]:[];return ops.sort((a,b)=>(a.createdAt||0)-(b.createdAt||0));}
export async function saveLocalFile(value:{id:string}){if(!database)throw Error('本地数据库不可用');const tx=database.transaction('files','readwrite');await new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error);tx.objectStore('files').put(value);});}
export async function localFiles<T>():Promise<T[]>{return database?await request(database.transaction('files').objectStore('files').getAll()) as T[]:[];}
export async function deleteLocalFile(id:string){if(!database)return;const tx=database.transaction('files','readwrite');await new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error);tx.onerror=()=>reject(tx.error);tx.objectStore('files').delete(id);});}
