import {Directory,Filesystem} from '@capacitor/filesystem';import {Capacitor} from '@capacitor/core';import {saveLocalFile,localFiles,deleteLocalFile,localOperations,commitLocal,readMetadata} from './local-database';import {api,jsonBody,ApiError} from './api';import {flushOperations,editLocally,type LocalOperation} from './offline-editing';import {catalogChanged} from './catalog-store';import {rememberRepertoire} from './repertoire-store';import type {TalentItem,ImportJob} from './types';import type {ItemRef} from './library-management';
export interface PendingFile {id:string;path?:string;blob?:Blob;name:string;mime:string;kind:string;itemId:string;state:string;jobId?:string;uploadId?:string;error?:string;title?:string;learningStatus?:string;createFields?:Record<string,unknown>;}
function base64(bytes:Uint8Array){let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(text);}
export async function queueFile(file:File,ref:ItemRef,kind:'MEDIA'|'SCORE'='MEDIA',options:{title?:string;learningStatus?:string;id?:string;createFields?:Record<string,unknown>}={}){
 if(!file.size)throw Error('文件为空，请重新选择');if(file.size>(kind==='SCORE'?25:512)*1024*1024)throw Error('文件超过大小限制');const id=options.id||crypto.randomUUID(),entry:PendingFile={id,name:file.name,mime:file.type||'application/octet-stream',kind:ref.kind+(kind==='SCORE'?':SCORE':''),itemId:ref.id,state:'pending',title:options.title||file.name.replace(/\.[^.]+$/,''),learningStatus:options.learningStatus,createFields:options.createFields};
 if(Capacitor.isNativePlatform()){entry.path=`dance-pending/${id}`;await Filesystem.mkdir({path:'dance-pending',directory:Directory.Data,recursive:true}).catch(()=>undefined);try{for(let offset=0;offset<file.size;offset+=262144){const data=base64(new Uint8Array(await file.slice(offset,offset+262144).arrayBuffer()));if(!offset)await Filesystem.writeFile({path:entry.path,directory:Directory.Data,data});else await Filesystem.appendFile({path:entry.path,directory:Directory.Data,data});}await saveLocalFile(entry);}catch(e){await Filesystem.deleteFile({path:entry.path,directory:Directory.Data}).catch(()=>undefined);throw e;}}
 else{entry.blob=file;await saveLocalFile(entry);}window.dispatchEvent(new Event('dance-files-changed'));void flushLocalFiles();return entry;
}
class LocalFileError extends Error {}
async function fileBody(entry:PendingFile){if(entry.blob)return entry.blob;try{const {uri}=await Filesystem.getUri({path:entry.path!,directory:Directory.Data});const response=await fetch(Capacitor.convertFileSrc(uri));if(!response.ok)throw Error();return await response.blob();}catch{throw new LocalFileError('手机副本无法读取，请移除待办并重新选择文件');}}
let task:Promise<void>|null=null;export function flushLocalFiles(){return task??=perform().finally(()=>{task=null;window.dispatchEvent(new Event('dance-files-changed'));});}
async function perform(){await flushOperations();for(const entry of await localFiles<PendingFile>()){if(['failed','duplicate'].includes(entry.state))continue;const ops=await localOperations<LocalOperation>();if(ops.some(o=>o.id===entry.itemId||o.action==='bulk'&&(o.fields?.refs as ItemRef[]||[]).some(r=>r.id===entry.itemId)))continue;try{
 const [kind,score]=entry.kind.split(':');if(score){await api(`/api/library/${kind}/${entry.itemId}/scores`,{method:'POST',headers:{'Content-Type':entry.mime,'X-Score-Id':entry.id},body:await fileBody(entry),signal:AbortSignal.timeout(120000)});if(kind!=='DANCE')rememberRepertoire(await api<TalentItem>(`/api/repertoire/${entry.itemId}`));}
 else{if(!entry.jobId){const job=await api<ImportJob>('/api/imports/file',{method:'POST',headers:{'Content-Type':entry.mime,'X-File-Name':encodeURIComponent(entry.name),'X-Import-Id':entry.uploadId||entry.id},body:await fileBody(entry),signal:AbortSignal.timeout(120000)});entry.jobId=job.id;await saveLocalFile(entry);}const job=await api<ImportJob>(`/api/imports/${entry.jobId}`);if(job.status==='FAILED'){entry.state='failed';entry.error='媒体无法读取，可重试或移除待办';await saveLocalFile(entry);continue;}if(job.status!=='READY')continue;if(entry.createFields&&job.duplicateRefs?.some(r=>r.kind===kind&&r.id!==entry.itemId)){entry.state='duplicate';entry.error='已有相同音频的曲目，请跳过重复文件';await saveLocalFile(entry);continue;}if(kind==='DANCE'){if(!job.duplicateId)await api(`/api/imports/${entry.jobId}/finalize`,{method:'POST',...jsonBody({title:entry.title,learningStatus:entry.learningStatus||'WANT_TO_LEARN'})});}else{if(entry.createFields){if(!JSON.parse(readMetadata('dance.repertoire-snapshot')||'[]').some((i:ItemRef)=>i.id===entry.itemId))await editLocally({kind:kind as 'GUITAR'|'VOCAL',id:entry.itemId},entry.createFields,'create');await flushOperations();if((await localOperations<LocalOperation>()).some(o=>o.id===entry.itemId))continue;entry.createFields=undefined;await saveLocalFile(entry);}const item=await api<TalentItem>(`/api/repertoire/${entry.itemId}/media`,{method:'POST',...jsonBody({importJobId:entry.jobId})});rememberRepertoire(item);}}
 const results=JSON.parse(readMetadata('dance.file-results')||'[]');await commitLocal({'dance.file-results':JSON.stringify([{id:entry.id,name:entry.name,title:entry.title,state:kind==='DANCE'&&entry.jobId?'已处理（重复曲目自动跳过）':'已收录',itemId:entry.itemId},...results.filter((r:{id:string})=>r.id!==entry.id)].slice(0,100))});await deleteLocalFile(entry.id);if(entry.path)await Filesystem.deleteFile({path:entry.path,directory:Directory.Data}).catch(()=>undefined);catalogChanged();
 }catch(error){if(error instanceof LocalFileError||error instanceof ApiError&&[400,404,413,415,422].includes(error.status)){entry.state='failed';entry.error=error.message;await saveLocalFile(entry);continue;}break;}}}
export async function retryPendingFiles(id?:string){for(const entry of await localFiles<PendingFile>())if(entry.state==='failed'&&(!id||entry.id===id)){entry.state='pending';entry.jobId=undefined;entry.uploadId=crypto.randomUUID();await saveLocalFile(entry);}return flushLocalFiles();}

export async function discardPendingFile(id:string){if(task)await task;const file=(await localFiles<PendingFile>()).find(f=>f.id===id);if(file?.path)try{await Filesystem.deleteFile({path:file.path,directory:Directory.Data});}catch(error){if((error as {code?:string})?.code!=='OS-PLUG-FILE-0008')throw error;}await deleteLocalFile(id);window.dispatchEvent(new Event('dance-files-changed'));}
