CREATE TABLE song_identities(id TEXT PRIMARY KEY,title TEXT,artist TEXT,recognition_status TEXT NOT NULL DEFAULT 'UNTRIED' CHECK(recognition_status IN('UNTRIED','MATCHED','AMBIGUOUS','FAILED','MANUAL')),provider TEXT,provider_ref TEXT,confidence REAL,cover_asset_id TEXT);
CREATE TABLE source_media(id TEXT PRIMARY KEY,source_kind TEXT NOT NULL,source_locator TEXT,internal_path TEXT,sha256 TEXT,duration_ms INTEGER NOT NULL CHECK(duration_ms>0),audio_codec TEXT,video_codec TEXT,status TEXT NOT NULL DEFAULT 'READY');
CREATE TABLE performance_clips(id TEXT PRIMARY KEY,source_media_id TEXT NOT NULL REFERENCES source_media(id),start_ms INTEGER NOT NULL CHECK(start_ms>=0),end_ms INTEGER NOT NULL CHECK(end_ms>start_ms),internal_audio_path TEXT NOT NULL,codec TEXT NOT NULL,source_preserving INTEGER NOT NULL CHECK(source_preserving IN(0,1)),sha256 TEXT NOT NULL,size_bytes INTEGER NOT NULL CHECK(size_bytes>0),duration_ms INTEGER NOT NULL,version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE assets(id TEXT PRIMARY KEY,kind TEXT NOT NULL,internal_path TEXT NOT NULL,sha256 TEXT NOT NULL,size_bytes INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE dance_items(id TEXT PRIMARY KEY,song_identity_id TEXT REFERENCES song_identities(id),source_media_id TEXT REFERENCES source_media(id),performance_clip_id TEXT NOT NULL REFERENCES performance_clips(id),title_override TEXT,learning_status TEXT NOT NULL DEFAULT 'WANT_TO_LEARN' CHECK(learning_status IN('CAN_DANCE','PRACTICING','WANT_TO_LEARN')),scene_mask INTEGER NOT NULL DEFAULT 0 CHECK(scene_mask BETWEEN 0 AND 15),cover_asset_id TEXT REFERENCES assets(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,deleted_at TEXT);
CREATE TABLE import_jobs(id TEXT PRIMARY KEY,source_kind TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('PENDING','PROCESSING','NEEDS_INPUT','READY','FAILED')),stage TEXT NOT NULL CHECK(stage IN('ACQUIRE','PROBE','EXTRACT','RECOGNIZE','COVER','REVIEW')),error_code TEXT,draft_json TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE tonight_playlist_items(dance_item_id TEXT PRIMARY KEY REFERENCES dance_items(id),position INTEGER NOT NULL UNIQUE CHECK(position>=0),updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE catalog_meta(singleton INTEGER PRIMARY KEY CHECK(singleton=1),catalog_version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO catalog_meta(singleton) VALUES(1);
