import {randomUUID,randomBytes,createHash,timingSafeEqual} from 'node:crypto';import {validateRefs,itemFor} from '../library/refs.mjs';import {getProgram,writeProgram} from '../program/service.mjs';import {bumpCatalog} from '../catalog.mjs';
export const tokenHash=token=>createHash('sha256').update(token).digest('hex');
export function authenticateOwner(db,token){if(typeof token!=='string'||token.length!==64)return false;const hash=tokenHash(token);return db.prepare('SELECT token_hash FROM owner_credentials').all().some(r=>timingSafeEqual(Buffer.from(r.token_hash),Buffer.from(hash)));}
export function pairOwner(db,code,expected){if(typeof code!=='string'||typeof expected!=='string'||!expected||code.length!==expected.length||!timingSafeEqual(Buffer.from(code),Buffer.from(expected)))throw Object.assign(Error('UNAUTHORIZED'),{status:401});const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO owner_credentials(token_hash) VALUES(?)').run(tokenHash(token));return {token};}
export function createRequestSession(db,refs,now=Date.now()){validateRefs(refs,{max:200});if(refs.some(r=>!itemFor(db,r)))throw Error('NOT_FOUND');const id=randomUUID(),token=randomBytes(24).toString('base64url'),expiresAt=now+24*3600000;db.prepare('INSERT INTO request_sessions(id,token,expires_at,subset_json) VALUES(?,?,?,?)').run(id,token,expiresAt,JSON.stringify(refs));return {id,token,expiresAt};}
function session(db,token,now){const row=db.prepare('SELECT * FROM request_sessions WHERE token=?').get(token);if(!row||row.closed||row.expires_at<=now)throw Object.assign(Error('NOT_FOUND'),{status:404});return row;}
export function publicSession(db,token,now=Date.now()){const row=session(db,token,now);return {expiresAt:row.expires_at,items:JSON.parse(row.subset_json).map(r=>{const item=itemFor(db,r);return item?{kind:r.kind,id:r.id,title:item.title}:null;}).filter(Boolean)};}
export function guestRequest(db,token,body,now=Date.now()){const row=session(db,token,now);if(!body||Object.keys(body).some(k=>!['visitor','kind','id','nickname','note'].includes(k))||typeof body.visitor!=='string'||!/^[0-9a-f-]{36}$/.test(body.visitor)||typeof body.nickname!=='string'||body.nickname.length>40||typeof body.note!=='string'||body.note.length>200)throw Error('BAD_REQUEST');validateRefs([{kind:body.kind,id:body.id}]);if(!JSON.parse(row.subset_json).some(r=>r.kind===body.kind&&r.id===body.id)||!itemFor(db,body))throw Error('NOT_FOUND');
 db.exec('BEGIN IMMEDIATE');try{const existing=db.prepare("SELECT id FROM guest_requests WHERE session_id=? AND visitor=? AND kind=? AND item_id=? AND state='PENDING'").get(row.id,body.visitor,body.kind,body.id);if(existing){db.exec('COMMIT');return {id:existing.id,state:'PENDING'};}if(db.prepare('SELECT count(*) AS n FROM guest_requests WHERE session_id=? AND visitor=? AND created_at>?').get(row.id,body.visitor,now-60000).n>=5)throw Object.assign(Error('RATE_LIMIT'),{status:429});if(db.prepare("SELECT count(*) AS n FROM guest_requests WHERE session_id=? AND state='PENDING'").get(row.id).n>=200)throw Object.assign(Error('QUEUE_FULL'),{status:429});const id=randomUUID();db.prepare('INSERT INTO guest_requests(id,session_id,visitor,kind,item_id,nickname,note,created_at) VALUES(?,?,?,?,?,?,?,?)').run(id,row.id,body.visitor,body.kind,body.id,body.nickname,body.note,now);db.exec('COMMIT');return {id,state:'PENDING'};}catch(e){db.exec('ROLLBACK');throw e;}}
export function decideRequest(db,id,decision){if(!['ACCEPTED','REJECTED'].includes(decision))throw Error('BAD_REQUEST');db.exec('BEGIN IMMEDIATE');try{const request=db.prepare('SELECT * FROM guest_requests WHERE id=?').get(id);if(!request)throw Error('NOT_FOUND');if(request.state==='PENDING'){if(decision==='ACCEPTED'){const ref={kind:request.kind,id:request.item_id};if(!itemFor(db,ref))throw Error('NOT_FOUND');const program=getProgram(db);if(!program.items.some(r=>r.kind===ref.kind&&r.id===ref.id)){if(program.items.length>=200)throw Error('QUEUE_FULL');writeProgram(db,[...program.items,ref]);bumpCatalog(db);}}db.prepare('UPDATE guest_requests SET state=? WHERE id=?').run(decision,id);}db.exec('COMMIT');return {state:request.state==='PENDING'?decision:request.state};}catch(e){db.exec('ROLLBACK');throw e;}}
