import {useEffect,useState} from 'react';import {Link} from 'react-router-dom';import {api,jsonBody} from '../lib/api';import {useCatalog} from '../lib/catalog-store';import {useRepertoire} from '../lib/repertoire-store';import {readDeviceSettings} from '../lib/device-settings';import {kindLabel} from '../lib/program';
interface Session {id:string;token:string;expiresAt:number;closed:number}interface GuestRequest {id:string;title:string;nickname:string;note:string;state:string}
export default function RequestAdminPage(){const {items:dances}=useCatalog(),{items:talents}=useRepertoire();const [selected,setSelected]=useState<Set<string>>(new Set()),[sessions,setSessions]=useState<Session[]>([]),[requests,setRequests]=useState<GuestRequest[]>([]),[message,setMessage]=useState(''),[qr,setQr]=useState(''),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[clearHistory,setClearHistory]=useState(false);const items=[...dances.map(i=>({...i,kind:'DANCE' as const})),...talents];
 async function refresh(){try{const data=await api<{sessions:Session[];requests:GuestRequest[]}>('/api/request-sessions');setSessions(data.sessions);setRequests(data.requests);}catch{setMessage('请先连接并配对 Mac Mini。');}}
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),15000);return()=>clearInterval(timer);},[]);
 async function show(session:Session){const address=(readDeviceSettings().apiEndpoint||window.location.origin)+`/request/${session.token}`;setUrl(address);const response=await api<{image:string}>(`/api/request-sessions/${session.id}/qr`);setQr(response.image);}
 async function create(){setBusy(true);try{const session=await api<Session>('/api/request-sessions',{method:'POST',...jsonBody({items:items.filter(i=>selected.has(i.id)).map(({kind,id})=>({kind,id}))})});await show(session);await refresh();setMessage('仅发布所选曲目，24 小时后过期；请让来宾连接同一 Wi-Fi。');}catch{setMessage('创建失败，请确认连接和设备配对。');}finally{setBusy(false);}}
 async function decide(id:string,decision:string){setBusy(true);try{await api(`/api/requests/${id}`,{method:'POST',...jsonBody({decision})});await refresh();}catch{setMessage('处理未完成，请重试。');}finally{setBusy(false);}}
 return <section><header className="page-header"><Link to="/settings">‹ 我的</Link><h1>扫码点歌</h1></header><p>默认不发布任何曲目。来宾只能看所选歌名和才艺类型，不能看你的谱、歌词、备注或媒体。</p>{message&&<p role="status">{message}</p>}{qr&&<div><img className="request-qr" src={qr} alt="点歌二维码"/><p className="request-url">{url}</p></div>}<details><summary>选择要发布的曲目（{selected.size}）</summary>{items.map(i=><label className="trash-row" key={i.id}><input type="checkbox" checked={selected.has(i.id)} onChange={()=>setSelected(old=>{const next=new Set(old);if(next.has(i.id))next.delete(i.id);else next.add(i.id);return next;})}/>{i.title} · {kindLabel(i.kind)}</label>)}</details><button className="primary" disabled={busy||!selected.size} onClick={()=>void create()}>生成本地点歌二维码</button><h2>开放记录</h2>{sessions.filter(s=>!s.closed&&s.expiresAt>Date.now()).map(s=><div className="button-row" key={s.id}><button onClick={()=>void show(s)}>显示二维码</button><button onClick={()=>void api(`/api/request-sessions/${s.id}`,{method:'DELETE'}).then(()=>{setQr('');setUrl('');return refresh();}).catch(()=>setMessage('关闭失败，请重试'))}>关闭点歌台</button></div>)}<h2>待处理点歌（{requests.filter(r=>r.state==='PENDING').length}）</h2>{requests.filter(r=>r.state==='PENDING').map(r=><div className="settings-block" key={r.id}><h3>{r.title}</h3><p>{r.nickname||'来宾'}：{r.note||'无留言'}</p><div className="button-row"><button disabled={busy} onClick={()=>void decide(r.id,'ACCEPTED')}>接受并加入节目单</button><button disabled={busy} onClick={()=>void decide(r.id,'REJECTED')}>拒绝</button></div></div>)}<h2>已处理记录（{requests.filter(r=>r.state!=='PENDING').length}）</h2><button disabled={busy||!requests.some(r=>r.state!=='PENDING')} onClick={()=>setClearHistory(true)}>清理已处理点歌</button>{clearHistory&&<div className="modal-backdrop"><section className="import-sheet" role="dialog" aria-modal="true" aria-label="清理已处理点歌"><h2>清理已处理点歌记录？</h2><p>保留未处理请求和今晚节目单。</p><div className="button-row"><button onClick={()=>setClearHistory(false)}>取消</button><button disabled={busy} onClick={()=>{setBusy(true);void api('/api/requests/history',{method:'DELETE'}).then(()=>{setClearHistory(false);return refresh();}).catch(()=>setMessage('清理失败，请重试')).finally(()=>setBusy(false));}}>确认清理点歌记录</button></div></section></div>}</section>;
}
