import MultiImportSheet from '../components/MultiImportSheet';
import BulkActionSheet from '../components/BulkActionSheet';
import BatchEditSheet, {type ClassificationChange} from '../components/BatchEditSheet';
import {bulkRequest,runBulk,addToProgram} from '../lib/library-management';
import {useEffect} from 'react';
import { playableTalent } from '../lib/repertoire-store';
import { playbackSource } from '../native/filesystem';
import { isItemPlayable, readCachedIndex } from '../lib/offline-manifest';
import { useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useRepertoire, talentLabel, talentStatuses } from '../lib/repertoire-store';
import TalentNav from '../components/TalentNav';
import CoverArt from '../components/CoverArt';
import LibraryFilters, { type LibraryFilterValue } from '../components/LibraryFilters';
export default function TalentLibraryPage() {
 const { kind: pathKind } = useParams(); const kind = pathKind === 'guitar' ? 'GUITAR' : 'VOCAL';
 const { items, error } = useRepertoire(); const [query, setQuery] = useState(''), [filters,setFilters]=useState<LibraryFilterValue>({status:null,scenes:[],demoOnly:false,cachedOnly:false});
 const [importing,setImporting]=useState(false),[adding,setAdding]=useState(false);
 const [batch,setBatch]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[editing,setEditing]=useState(false),[deleting,setDeleting]=useState(false),[message,setMessage]=useState('');
 const request=useRef<ReturnType<typeof bulkRequest>|null>(null);
 useEffect(()=>{setSelected(new Set());setEditing(false);setDeleting(false);setBatch(false);setPlaying('');if(audio.current?.getAttribute('src'))audio.current.pause();},[kind]);
 const clear=()=>setSelected(new Set());
 const save=async(fields:ClassificationChange)=>{request.current??=bulkRequest('update',[...selected].map(id=>({kind,id})),fields);await runBulk(request.current);request.current=null;setEditing(false);clear();setMessage('已修改所选曲目');};
 const audio = useRef<HTMLAudioElement>(null); const [playing, setPlaying] = useState(''), [paused, setPaused] = useState(true), [playError, setPlayError] = useState('');
 const play = (item: typeof items[number]) => { const source = playableTalent(item), a = audio.current; if (!source || !a) return; setPlayError(''); if (playing === item.id && !a.paused) { a.pause(); return; } a.src = playbackSource(source, readCachedIndex()); setPlaying(item.id); void a.play().catch(() => setPlayError('请检查连接或到“我的”下载全部音乐')); };
 const filtered = items.filter(item => item.kind === kind && (!filters.status || item.learningStatus === filters.status)&&(!filters.demoOnly||item.isDemo)&&(!filters.cachedOnly||(playableTalent(item)&&isItemPlayable(playableTalent(item)!,readCachedIndex()))) && `${item.title} ${item.artist}`.toLowerCase().includes(query.toLowerCase().trim()));
 return <section><header className="library-header"><TalentNav /><button className="batch-entry" onClick={()=>{audio.current?.pause();setPlaying('');setBatch(!batch);clear();}}>{batch?'退出批量':'批量管理'}</button><button aria-label={`收录${talentLabel(kind)}曲目`} onClick={()=>setAdding(true)}>＋</button></header>
 <div className="library-search"><input className="search" type="search" aria-label="搜索曲目" placeholder="搜索歌名或歌手" value={query} onChange={e => {setQuery(e.target.value);clear();}} /><LibraryFilters kind={kind} value={filters} onChange={v=>{setFilters(v);clear();}}/></div>
 {message&&<p role="status">{message}</p>}{batch&&<div className="batch-toolbar"><span>点击卡片选择 · 当前 {filtered.length} 首</span><button onClick={()=>setSelected(new Set(filtered.map(i=>i.id)))}>全选当前结果</button><button onClick={clear}>清空选择</button></div>}
 {error && <p className="notice">{error}</p>}
 {filtered.length ? <div className={`card-grid talent-grid${kind === 'VOCAL' ? ' vocal-grid' : ''}`}>{filtered.map(item => <article className={`dance-card${playing === item.id ? ' dance-card--active' : ''}`} key={item.id}>{batch?<button className="dance-card__select" aria-label={`${selected.has(item.id)?'取消选择':'选择'} ${item.title}`} aria-pressed={selected.has(item.id)} onClick={()=>setSelected(old=>{const next=new Set(old);if(next.has(item.id))next.delete(item.id);else next.add(item.id);return next;})}><CoverArt title={item.title}/><span>{selected.has(item.id)?'✓ 已选':'选择'}</span></button>:<><Link className="dance-card__body" to={`/repertoire/item/${item.id}`} aria-label={`查看 ${item.title}`}><div className="dance-card__cover"><CoverArt title={item.title} />{item.isDemo&&<span className="demo-badge">示例</span>}{item.audio&&<span className="duration">{Math.floor(item.durationMs/60000)}:{String(Math.round(item.durationMs/1000)%60).padStart(2,'0')}</span>}</div>{item.artist && !['未识别','未填写歌手'].includes(item.artist)&&<p>{item.artist}</p>}<div className="dance-card__labels"><span>{talentStatuses(kind).find(s => s.id === item.learningStatus)?.label}</span>{item.performanceKey && <span>{item.performanceKey}调</span>}{kind === 'GUITAR' && <span>Capo {item.capo}</span>}{!item.audio&&<span>文本曲目</span>}</div></Link>{item.audio && <button className={kind === 'VOCAL' ? `quick-play${playing === item.id && !paused ? ' quick-play--active' : ''}` : 'icon-link'} onClick={() => play(item)} aria-pressed={kind === 'VOCAL' ? playing === item.id && !paused : undefined} aria-label={`${playing === item.id && !paused ? '暂停' : '播放'} ${item.title}`}>{kind === 'VOCAL' ? (playing === item.id && !paused ? '⏸' : '▶') : (playing === item.id && !paused ? '⏸ 暂停' : '▶ 播放')}</button>}</>}</article>)}</div> : <div className="empty-library"><h2>{query || filters.status || filters.demoOnly || filters.cachedOnly ? '没有符合筛选的曲目' : `还没有${talentLabel(kind)}曲目`}</h2><p>可以先保存文本谱或歌词，再添加自己的练习音频。</p><Link className="icon-link primary" to={`/repertoire/${kind === 'GUITAR' ? 'guitar' : 'vocal'}/new`}>＋ 收录曲目</Link></div>}
 {batch&&<div className="batch-actions"><span>已选 {selected.size} 首</span><button disabled={!selected.size} onClick={()=>{request.current=null;setEditing(true);}}>修改分类</button><button disabled={!selected.size} onClick={()=>void addToProgram([...selected].map(id=>({kind,id}))).then(()=>setMessage('已加入今晚节目单')).catch(()=>setMessage('加入失败，请连接服务器重试'))}>加入节目单</button><button disabled={!selected.size} onClick={()=>setDeleting(true)}>删除</button></div>}
 {adding&&<div className="modal-backdrop"><section className="import-sheet" role="dialog" aria-modal="true" aria-label="收录曲目"><h2>收录{talentLabel(kind)}曲目</h2><Link className="icon-link" to={`/repertoire/${kind==='GUITAR'?'guitar':'vocal'}/new`}>先保存文本谱 / 歌词</Link><button onClick={()=>{setAdding(false);setImporting(true);}}>批量收录音频 / 视频</button><button onClick={()=>setAdding(false)}>取消</button></section></div>}{importing&&<MultiImportSheet kind={kind} onClose={()=>setImporting(false)}/>}{editing&&<BatchEditSheet kind={kind} count={selected.size} onClose={()=>{setEditing(false);request.current=null;}} onSave={save}/>}
 {deleting&&<BulkActionSheet action="trash" items={items.filter(i=>selected.has(i.id)).map(i=>({...i,kind}))} onClose={()=>setDeleting(false)} onDone={()=>{setDeleting(false);clear();setMessage('已移入回收站');}}/>}
 <div className="mini-player" hidden={!playing}><span className="mini-player__title">{items.find(item => item.id === playing)?.title}</span><audio ref={audio} controls onPlay={() => setPaused(false)} onPause={() => setPaused(true)} onEnded={() => { setPaused(true); setPlaying(''); }} />{playError && <p role="alert">{playError}</p>}</div></section>;
}
