import {useEffect,useState,useRef} from 'react';
import {useCatalog} from '../lib/catalog-store';import {useRepertoire} from '../lib/repertoire-store';
import {fetchProgram,saveProgram,storedProgram,kindLabel,programAudio,type ProgramItem} from '../lib/program';
import {prepareOffline} from '../lib/sync';import {isItemPlayable,readCachedIndex} from '../lib/offline-manifest';
import {moveItem} from '../lib/playlist';import type {LibraryKind} from '../lib/library-management';
export default function TonightPlaylistPage(){const {items:dances}=useCatalog(),{items:talents}=useRepertoire();const [program,setProgram]=useState(storedProgram),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[kind,setKind]=useState<LibraryKind|'ALL'>('ALL'),[selected,setSelected]=useState<Set<string>>(new Set()),[confirm,setConfirm]=useState(false);
 const dragging=useRef<{index:number;pointer:number}|null>(null);const [dragIndex,setDragIndex]=useState<number|null>(null);
 function startDrag(event:React.PointerEvent<HTMLButtonElement>,index:number){event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);dragging.current={index,pointer:event.pointerId};setDragIndex(index);}
 function endDrag(event:React.PointerEvent<HTMLButtonElement>){const drag=dragging.current;dragging.current=null;setDragIndex(null);if(!drag)return;const row=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>('[data-program-index]');if(row)void persist(moveItem(program.items,drag.index,Number(row.dataset.programIndex)));}
 const catalog:ProgramItem[]=[...dances.map(i=>({...i,kind:'DANCE' as const})),...talents];const items=program.items.map(r=>catalog.find(i=>i.kind===r.kind&&i.id===r.id)).filter((i):i is ProgramItem=>!!i);const cached=readCachedIndex();
 useEffect(()=>{const changed=()=>setProgram(storedProgram());window.addEventListener('dance-program-changed',changed);fetchProgram().then(setProgram).catch(()=>setMessage('当前显示手机保存的节目单'));return()=>window.removeEventListener('dance-program-changed',changed);},[]);
 async function persist(refs:typeof program.items){setBusy(true);setMessage('');try{setProgram(await saveProgram({...program,items:refs}));setSelected(new Set());setConfirm(false);}catch{setMessage('保存失败或节目单已在另一端修改，当前顺序保留；请刷新后重试。');}finally{setBusy(false);}}
 async function prepare(){setBusy(true);try{const result=items.length?await prepareOffline(items,(done,total)=>setMessage(`正在缓存 ${done}/${total}`)):{ready:true};setMessage(result.ready?'节目单已准备好，音乐可离线播放；文本曲目无需音频。':'仍有音乐缺失或损坏，请重试。');}catch{setMessage('准备失败，请检查连接后重试。');}finally{setBusy(false);}}
 const remaining=catalog.filter(i=>!program.items.some(r=>r.kind===i.kind&&r.id===i.id)&&(kind==='ALL'||i.kind===kind)&&`${i.title} ${i.artist}`.toLowerCase().includes(query.toLowerCase()));
 return <section><header className="page-header"><h1>今晚节目单</h1><button disabled={busy||!items.length} onClick={()=>setConfirm(true)}>清空</button></header><button className="primary" disabled={busy||!items.length} onClick={()=>void prepare()}>准备离线演出</button>{message&&<p role="status">{message}</p>}<ol className="playlist">{items.map((item,index)=><li className={`playlist__row${dragIndex===index?' playlist__row--dragging':''}`} data-program-index={index} key={item.kind+item.id}><button className="playlist__drag" aria-label={`拖动排序 ${item.title}`} disabled={busy} onPointerDown={e=>startDrag(e,index)} onPointerUp={endDrag} onPointerCancel={()=>{dragging.current=null;setDragIndex(null);}}>⠿</button><span className="playlist__title">{item.title}<small>{kindLabel(item.kind)} · {programAudio(item)?isItemPlayable(programAudio(item)!,cached)?'已缓存':'未缓存':'文本曲目'}</small></span><span className="playlist__move"><button disabled={busy||index===0} aria-label={`上移 ${item.title}`} onClick={()=>void persist(moveItem(program.items,index,index-1))}>↑</button><button disabled={busy||index===items.length-1} aria-label={`下移 ${item.title}`} onClick={()=>void persist(moveItem(program.items,index,index+1))}>↓</button><button disabled={busy} aria-label={`移出 ${item.title}`} onClick={()=>void persist(program.items.filter(r=>!(r.id===item.id&&r.kind===item.kind)))}>×</button></span></li>)}</ol>{!items.length&&<p>节目单为空，从下面选择舞蹈、吉他或唱歌。</p>}<h2>加入节目单</h2><div className="library-search"><input placeholder="搜索曲目" value={query} onChange={e=>{setQuery(e.target.value);setSelected(new Set());}}/><select aria-label="才艺类型" value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setSelected(new Set());}}>{(['ALL','DANCE','GUITAR','VOCAL'] as const).map(k=><option key={k} value={k}>{k==='ALL'?'全部':kindLabel(k)}</option>)}</select></div><div className="button-row"><button disabled={busy} onClick={()=>setSelected(new Set(remaining.map(i=>i.id)))}>全选当前结果</button><button disabled={busy||!selected.size} onClick={()=>void persist([...program.items,...remaining.filter(i=>selected.has(i.id)).map(({kind,id})=>({kind,id}))])}>加入所选（{selected.size}）</button></div>{remaining.map(i=><label className="trash-row" key={i.id}><input type="checkbox" checked={selected.has(i.id)} onChange={()=>setSelected(old=>{const next=new Set(old);if(next.has(i.id))next.delete(i.id);else next.add(i.id);return next;})}/>{i.title} · {kindLabel(i.kind)}</label>)}{confirm&&<div className="modal-backdrop"><section className="import-sheet" role="dialog" aria-modal="true" aria-label="清空节目单"><h2>清空今晚节目单？</h2><p>只移除节目单中的 {items.length} 项，曲库内容保留。</p><div className="button-row"><button onClick={()=>setConfirm(false)}>取消</button><button disabled={busy} onClick={()=>void persist([])}>确认清空</button></div></section></div>}</section>;
}
