import {localOperations} from '../lib/local-database';
import type {LocalOperation} from '../lib/offline-editing';
import {readMetadata,writeMetadata} from '../lib/local-database';
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../lib/api';
import type {TrashItem} from '../lib/library-management';
import BulkActionSheet from '../components/BulkActionSheet';
const unique=(items:TrashItem[])=>[...new Map(items.map(i=>[i.kind+':'+i.id,i])).values()];
export default function TrashPage(){const [items,setItems]=useState<TrashItem[]>(()=>unique(JSON.parse(readMetadata('dance.trash')||'[]'))),[selected,setSelected]=useState<Set<string>>(new Set()),[error,setError]=useState(''),[query,setQuery]=useState(''),[action,setAction]=useState<'restore'|'purge'|null>(null);
 const visible=items.filter(i=>`${i.title} ${i.kind==='DANCE'?'舞蹈':i.kind==='GUITAR'?'吉他':'唱歌'}`.toLowerCase().includes(query.toLowerCase()));
 const refresh=async()=>{try{const response=await api<{items:TrashItem[]}>('/api/library/trash'),ops=await localOperations<LocalOperation>();const local=JSON.parse(readMetadata('dance.trash')||'[]') as TrashItem[],active=[...JSON.parse(readMetadata('dance.catalog-snapshot')||'[]'),...JSON.parse(readMetadata('dance.repertoire-snapshot')||'[]')];const restores=new Set(ops.flatMap(o=>o.action==='restore'?[o.id]:o.action==='bulk'&&o.fields?.action==='restore'?(o.fields.refs as {id:string}[]).map(r=>r.id):[]));const pending=new Set(ops.flatMap(o=>o.action==='trash'?[o.id]:o.action==='bulk'&&o.fields?.action==='trash'?(o.fields.refs as {id:string}[]).map(r=>r.id):[]));const items=unique([...response.items.filter(i=>!restores.has(i.id)&&!pending.has(i.id)&&!active.some(a=>a.id===i.id&&(a.revision||0)>=(i.revision||0))),...local.filter(i=>pending.has(i.id))]);writeMetadata('dance.trash',JSON.stringify(items));setItems(items);setError('');}catch{setItems(unique(JSON.parse(readMetadata('dance.trash')||'[]')));setError('当前显示手机回收站，联网后同步。');}};
 useEffect(()=>{void refresh();window.addEventListener('dance-sync-changed',refresh);return()=>window.removeEventListener('dance-sync-changed',refresh);},[]);
 return <section><header className="page-header"><Link to="/settings">‹ 我的</Link><h1>回收站</h1></header><p>删除的记录保留在这里，由你决定何时清理。</p>{error&&<p role="alert">{error}<button onClick={()=>void refresh()}>重试</button></p>}<input type="search" placeholder="搜索回收站曲名 / 才艺" value={query} onChange={e=>{setQuery(e.target.value);setSelected(new Set());}}/><div className="button-row"><button onClick={()=>setSelected(new Set(visible.map(i=>i.id)))}>全选</button><button disabled={!selected.size} onClick={()=>setAction('restore')}>恢复（{selected.size}）</button><button disabled={!selected.size} onClick={()=>setAction('purge')}>永久删除记录</button></div>{visible.map(i=><label className="trash-row" key={i.id}><input type="checkbox" checked={selected.has(i.id)} onChange={()=>setSelected(old=>{const next=new Set(old);if(next.has(i.id))next.delete(i.id);else next.add(i.id);return next;})}/><span>{i.title}<small>{i.kind==='DANCE'?'舞蹈':i.kind==='GUITAR'?'吉他':'唱歌'} · {i.deletedAt}</small></span></label>)}{!items.length&&!error&&<p>回收站为空</p>}{action&&<BulkActionSheet action={action} items={items.filter(i=>selected.has(i.id))} onClose={()=>setAction(null)} onDone={()=>{setAction(null);setSelected(new Set());void refresh();}}/>}</section>;
}
