import {useEffect,useRef,useState} from 'react';
import {getDocument,GlobalWorkerOptions,type PDFDocumentProxy} from 'pdfjs-dist';
import worker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import type {ScoreAsset} from '../lib/types';import {readCachedIndex,isMediaReady} from '../lib/offline-manifest';import {offlineUrl,cachedFileValid} from '../native/filesystem';import {mediaUrl} from '../lib/api';
GlobalWorkerOptions.workerSrc=worker;
export default function ScoreReader({asset,offline=false}:{asset:ScoreAsset;offline?:boolean}){const [doc,setDoc]=useState<PDFDocumentProxy|null>(null),[page,setPage]=useState(()=>Number(localStorage.getItem('dance.score-page.'+asset.id)||1)),[zoom,setZoom]=useState(1),[url,setUrl]=useState(''),[error,setError]=useState('');const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{let active=true;let task:ReturnType<typeof getDocument>|undefined;setError('');setDoc(null);setUrl('');void(async()=>{const cached=readCachedIndex(),hit=cached[asset.url];const ready=hit&&isMediaReady({...asset,key:asset.url,kind:'score'},cached)&&await cachedFileValid({...asset,key:asset.url,kind:'score'},hit);if(offline&&!ready)throw Error('此谱还未下载，请先准备离线演出。');const source=ready?offlineUrl(hit.uri):mediaUrl(asset.url);if(!active)return;setUrl(source);if(asset.kind==='PDF'){task=getDocument({url:source,cMapUrl:'/pdf/cmaps/',cMapPacked:true,standardFontDataUrl:'/pdf/standard_fonts/',wasmUrl:'/pdf/wasm/',enableXfa:false});const pdf=await task.promise;if(active){setDoc(pdf);setPage(Math.min(Math.max(Number(localStorage.getItem('dance.score-page.'+asset.id)||1),1),pdf.numPages));}}})().catch(e=>{if(active)setError(e instanceof Error?e.message:'谱无法读取');});return()=>{active=false;void task?.destroy();};},[asset.id,asset.kind,asset.url,offline,asset]);
 useEffect(()=>{if(!doc||!canvas.current)return;let render:ReturnType<Awaited<ReturnType<PDFDocumentProxy['getPage']>>['render']>|undefined;let active=true;void doc.getPage(page).then(p=>{if(!active||!canvas.current)return;const viewport=p.getViewport({scale:zoom*1.5}),c=canvas.current;c.width=viewport.width;c.height=viewport.height;render=p.render({canvas:c,viewport});return render.promise.finally(()=>p.cleanup());}).catch(e=>{if(active&&e?.name!=='RenderingCancelledException')setError('当前页无法读取');});localStorage.setItem('dance.score-page.'+asset.id,String(page));return()=>{active=false;render?.cancel();};},[doc,page,zoom,asset.id]);
 return <div className="score-reader">{error&&<p role="alert">{error}</p>}<div className="button-row"><button onClick={()=>setZoom(Math.max(.5,zoom-.25))}>缩小</button><button onClick={()=>setZoom(Math.min(3,zoom+.25))}>放大</button>{doc&&<><button disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</button><span>{page}/{doc.numPages}</span><button disabled={page>=doc.numPages} onClick={()=>setPage(page+1)}>下一页</button></>}</div><div className="score-reader__surface">{asset.kind==='PDF'?<canvas ref={canvas}/>:url&&<img style={{width:`${zoom*100}%`,maxWidth:'none'}} src={url} alt="乐谱" onError={()=>setError('谱图无法读取，请重新下载或检查连接。')}/>}</div></div>;
}
