import {useEffect,useState} from 'react';
import {retryPendingFiles,discardPendingFile,type PendingFile} from '../lib/offline-files';
import {localFiles,localOperations,readMetadata} from '../lib/local-database';
import {flushOperations,resolveOperation,retryOperation,type LocalOperation} from '../lib/offline-editing';
const names:Record<string,string>={title:'歌名',artist:'歌手',learningStatus:'学习状态',sceneTags:'场景标签',sceneMode:'标签操作',originalKey:'原调',performanceKey:'演奏 / 演唱调',capo:'Capo',scoreText:'谱 / 歌词',notes:'备注',audioRole:'音频用途',items:'节目单顺序'};
export default function SyncControls(){
 const [results,setResults]=useState<{id:string;name:string;state:string}[]>([]),[files,setFiles]=useState<PendingFile[]>([]),[ops,setOps]=useState<LocalOperation[]>([]),[error,setError]=useState(''),[chosen,setChosen]=useState<Record<string,boolean>>({}),[discard,setDiscard]=useState<PendingFile|null>(null);
 const refresh=()=>{setResults(JSON.parse(readMetadata('dance.file-results')||'[]'));void localOperations<LocalOperation>().then(setOps);void localFiles<PendingFile>().then(setFiles);};
 useEffect(()=>{refresh();window.addEventListener('dance-sync-changed',refresh);window.addEventListener('dance-files-changed',refresh);const storage=()=>setError('手机存储未能保存，请检查空间后重试。');window.addEventListener('dance-storage-error',storage);return()=>{window.removeEventListener('dance-sync-changed',refresh);window.removeEventListener('dance-files-changed',refresh);window.removeEventListener('dance-storage-error',storage);};},[]);
 async function resolve(op:LocalOperation,fields:Record<string,unknown>|null){try{await resolveOperation(op,fields);refresh();}catch{setError('选择尚未保存，请重试。');}}
 return <div className="settings-block"><h2>同步与待办</h2><p>{ops.length?`待同步 ${ops.length} 项`:'手机修改已同步'}</p><button onClick={()=>void flushOperations().then(refresh)}>重试同步</button><p>待处理文件 {files.length} 个</p><button disabled={!files.length} onClick={()=>void retryPendingFiles().then(refresh)}>重试文件处理</button>{files.map(f=><div key={f.id}><p>{f.name} · {['failed','duplicate'].includes(f.state)?f.error:'已保存，等待服务器处理'}</p><button onClick={()=>setDiscard(f)}>{f.state==='duplicate'?'跳过重复文件':'移除文件待办'}</button>{f.state==='failed'&&<button onClick={()=>void retryPendingFiles(f.id).then(refresh)}>重试此文件</button>}</div>)}<details><summary>最近处理结果（{results.length}）</summary>{results.slice(0,20).map(r=><p key={r.id}>{r.name} · {r.state}</p>)}</details>{error&&<p role="alert">{error}</p>}{ops.filter(o=>o.state==='failed').map(op=><div key={op.operationId}><p role="alert">{op.error}；手机内容仍保留。</p><button onClick={()=>void retryOperation(op).then(refresh)}>重试此项修改</button></div>)}{ops.filter(o=>o.state==='conflict').map(op=>{
 const fields=(op.action==='bulk'?op.fields?.fields:op.fields) as Record<string,unknown>||{},serverItems=op.action==='bulk'?op.server?.items:null;
 return <div className="sync-conflict" key={op.operationId}><h3>两端修改冲突</h3><p>{op.action==='bulk'?`整批 ${(op.fields?.refs as unknown[])?.length||0} 项`:String(op.server?.title||op.id)}；请选择要保留的版本。</p>{!!op.server?.deletedAt&&<p>Mac 上此曲目已删除。采用手机修改会恢复曲目。</p>}{!Object.keys(fields).length&&<p>手机操作：{op.action==='bulk'?String(op.fields?.action):op.action}</p>}{Object.entries(fields).map(([key,value])=><label className="check-row" key={key}><input type="checkbox" checked={!!chosen[op.operationId+key]} onChange={e=>setChosen({...chosen,[op.operationId+key]:e.target.checked})}/><span>{names[key]||key}<br/>手机：{JSON.stringify(value)}<br/>Mac：{JSON.stringify(serverItems? (serverItems as Record<string,unknown>[]).map(i=>({title:i.title,value:i[key]})):op.server?.[key])??'无'}</span></label>)}<div className="button-row"><button onClick={()=>void resolve(op,null)}>采用 Mac 版本</button><button disabled={!op.server&&op.kind==='DANCE'&&op.action!=='bulk'} onClick={()=>void resolve(op,fields)}>采用手机修改</button><button disabled={!Object.keys(fields).some(k=>chosen[op.operationId+k])} onClick={()=>void resolve(op,Object.fromEntries(Object.entries(fields).filter(([k])=>chosen[op.operationId+k])))}>仅合并勾选字段</button></div></div>;
 })}{discard&&<div className="modal-backdrop"><section className="import-sheet" role="dialog" aria-modal="true" aria-label="移除文件待办"><h2>移除 {discard.name}？</h2><p>删除手机待处理副本，原文件和曲库记录保留。</p><div className="button-row"><button onClick={()=>setDiscard(null)}>取消</button><button onClick={()=>void discardPendingFile(discard.id).then(()=>{setDiscard(null);refresh();}).catch(()=>setError('尚未移除，请重试。'))}>确认移除待办</button></div></section></div>}</div>;
}
