import {randomUUID} from 'node:crypto';import {mkdirSync,writeFileSync,unlinkSync} from 'node:fs';import {join,resolve} from 'node:path';
import {fileIdentity} from '../media/ffmpeg.mjs';import {itemFor,validateRefs} from '../library/refs.mjs';import {bumpCatalog} from '../catalog.mjs';
export function listScores(db,ref){return db.prepare('SELECT a.*,l.position FROM score_links l JOIN score_assets a ON a.id=l.asset_id WHERE l.kind=? AND l.item_id=? ORDER BY l.position').all(ref.kind,ref.id).map(a=>({id:a.id,kind:a.kind,mime:a.mime,url:`/api/media/score/${a.id}`,sha256:a.sha256,sizeBytes:a.size_bytes,pages:a.pages,version:1}));}
export async function addScore(db,root,ref,req){validateRefs([ref]);if(!itemFor(db,ref))throw Error('NOT_FOUND');const clientId=req.headers?.['x-score-id'];if(clientId!==undefined&&(typeof clientId!=='string'||!/^[0-9a-f-]{36}$/.test(clientId)))throw Error('BAD_REQUEST');if(clientId&&listScores(db,ref).some(s=>s.id===clientId))return listScores(db,ref);let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>25*1024*1024)throw Error('UPLOAD_TOO_LARGE');chunks.push(chunk);}const buffer=Buffer.concat(chunks);let kind,mime,pages=1;
 if(buffer.subarray(0,5).toString()==='%PDF-'){kind='PDF';mime='application/pdf';const {getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs');const task=getDocument({data:new Uint8Array(buffer),standardFontDataUrl:resolve('node_modules/pdfjs-dist/standard_fonts')+'/',useSystemFonts:false,disableFontFace:true});let doc;try{doc=await task.promise;pages=doc.numPages;if(pages>100)throw Error('TOO_MANY_PAGES');for(let i=1;i<=pages;i++)await (await doc.getPage(i)).getOperatorList();}finally{await task.destroy();}}
 else {if(size>10*1024*1024)throw Error('UPLOAD_TOO_LARGE');const {execFile}=await import('node:child_process');const {promisify}=await import('node:util');const run=promisify(execFile);mime=buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?'image/png':buffer[0]===255&&buffer[1]===216?'image/jpeg':buffer.subarray(0,4).toString()==='RIFF'&&buffer.subarray(8,12).toString()==='WEBP'?'image/webp':null;if(!mime)throw Error('INVALID_MEDIA');kind='IMAGE';mkdirSync(join(root,'scores'),{recursive:true});const temp=join(root,'scores',randomUUID()+'.check');writeFileSync(temp,buffer);try{await run('ffmpeg',['-v','error','-nostdin','-i',temp,'-frames:v','1','-f','null','-'],{timeout:30000,maxBuffer:1024*1024});}finally{unlinkSync(temp);}}
 const id=clientId||randomUUID(),relative=`scores/${id}`,path=join(root,relative);mkdirSync(join(root,'scores'),{recursive:true});writeFileSync(path,buffer,{flag:'wx'});const hash=await fileIdentity(path);db.exec('BEGIN IMMEDIATE');try{db.prepare('INSERT INTO score_assets(id,kind,mime,internal_path,sha256,size_bytes,pages) VALUES(?,?,?,?,?,?,?)').run(id,kind,mime,relative,hash.sha256,size,pages);const position=db.prepare('SELECT COALESCE(MAX(position),-1)+1 AS p FROM score_links WHERE kind=? AND item_id=?').get(ref.kind,ref.id).p;db.prepare('INSERT INTO score_links VALUES(?,?,?,?)').run(ref.kind,ref.id,id,position);bumpCatalog(db);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');unlinkSync(path);throw e;}return listScores(db,ref);
}
export function setScores(db,ref,ids){validateRefs([ref]);if(!itemFor(db,ref)||!Array.isArray(ids)||new Set(ids).size!==ids.length)throw Error('BAD_REQUEST');const allowed=listScores(db,ref).map(i=>i.id);if(ids.some(id=>!allowed.includes(id)))throw Error('BAD_REQUEST');db.exec('BEGIN IMMEDIATE');try{db.prepare('DELETE FROM score_links WHERE kind=? AND item_id=?').run(ref.kind,ref.id);ids.forEach((id,n)=>db.prepare('INSERT INTO score_links VALUES(?,?,?,?)').run(ref.kind,ref.id,id,n));bumpCatalog(db);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return listScores(db,ref);}
